name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: dev-sockets  # Hacer checkout de la rama específica dev-sockets
          fetch-depth: 0    # Obtener el historial completo para la rama

      - name: Add upstream remote
        run: git remote add upstream https://github.com/AllianceBioversityCIAT/one-cgiar-microservices.git

      - name: Fetch upstream changes
        run: git fetch upstream dev-sockets

      - name: Merge upstream/dev-sockets into dev-sockets
        run: git merge upstream/dev-sockets || git merge --abort

      - name: Push changes to fork
        run: git push origin dev-sockets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
