name: Sync Fork

on:
  schedule:
    - cron: '*/10 * * * *'  
  workflow_dispatch:  

jobs:
  sync-fork:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Checkout fork repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: dev-sockets  # Solo sincronizar la rama dev-sockets
          fetch-depth: 0

      - name: Add upstream remote
        run: git remote add upstream https://github.com/AllianceBioversityCIAT/one-cgiar-microservices.git

      - name: Fetch upstream changes
        run: git fetch upstream dev-sockets

      - name: Check for differences between fork and upstream
        id: check_diff
        run: |
          git fetch origin dev-sockets
          DIFF=$(git diff --name-only origin/dev-sockets upstream/dev-sockets)
          if [ -z "$DIFF" ]; then
            echo "No changes found"
            echo "::set-output name=changes::false"
          else
            echo "Changes found"
            echo "::set-output name=changes::true"
          fi

      - name: Sync dev-sockets branch if differences found
        if: steps.check_diff.outputs.changes == 'true' 
        run: |
          git merge upstream/dev-sockets || git merge --abort
          git push origin dev-sockets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
